# Generated by Django 5.1 on 2026-06-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountuser',
            table='account_user',
        ),
    ]
