# Generated by Django 5.1 on 2026-06-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accountuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(db_index=True, max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'administrator_admin',
            },
        ),
    ]
