# Generated by Django 5.1 on 2026-06-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsincart',
            old_name='AccountUser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='AccountUser',
            new_name='user',
        ),
    ]
